AllCops:
  Exclude:
    - "db/**/*"
    - "bin/**/*"
    - "config/**/*"
    - "vendor/bundle/**/*"

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Style/MultilineBlockChain:
  Exclude:
    - "spec/**/*"

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Naming/MethodParameterName:
  AllowedNames: x, y

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/ClassAndModuleChildren:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/LineLength:
  Enabled: false
